replicaCount: 0

additionalServerOptions: >-
  -Djgroups.dns.query=sso-keycloak-ping.eb75ad-dev.svc.cluster.local

extraEnvs:
  - name: KC_HOSTNAME
    value: https://dev.loginproxy.gov.bc.ca/auth/
  - name: KC_HOSTNAME_ADMIN
    value: https://dev.loginproxy.gov.bc.ca/auth/
  - name: QUARKUS_LOG_FILE_ROTATION_MAX_BACKUP_INDEX
    value: "21"
  - name: QUARKUS_LOG_FILE_ROTATION_MAX_FILE_SIZE
    value: 300M
  - name: QUARKUS_LOG_FILE_ROTATION_FILE_SUFFIX
    value: .zip
  - name: KC_SPI_CONNECTIONS_HTTP_CLIENT_DEFAULT_CONNECTION_TTL_MILLIS
    value: "300000"
  - name: KC_SPI_CONNECTIONS_HTTP_CLIENT_DEFAULT_SOCKET_TIMEOUT_MILLIS
    value: "60000"
  ## If debugging needs to be done without the use of the vanity urls, use the following KC_HOSTNAMES
  # - name: KC_HOSTNAME
  #   value: https://sso-keycloak-eb75ad-dev.apps.golddr.devops.gov.bc.ca/auth/
  # - name: KC_HOSTNAME_ADMIN
  #   value: https://sso-keycloak-eb75ad-dev.apps.golddr.devops.gov.bc.ca/auth/

resources:
  limits:
    cpu: 4

maintenancePage:
  enabled: true
  active: true

persistentLog:
  size: 15Gi

patroni:
  replicaCount: 3

  persistentVolume:
    size: 18Gi

  podDisruptionBudget:
    enabled: false

  transportServerClaim:
    enabled: false
